import type { LearningRecord, StudyEvent, Word, WordBook } from "./types";

export const mockWordBooks: WordBook[] = [
  {
    id: "cet4-core",
    name: "CET-4 Core 500",
    description: "College English Test Band 4 high-frequency vocabulary",
    wordCount: 500,
    category: "cet",
  },
  {
    id: "ielts-bridge",
    name: "IELTS Bridge 300",
    description: "Bridge words for IELTS reading and listening",
    wordCount: 300,
    category: "exam",
  },
  {
    id: "daily-english",
    name: "Daily English 400",
    description: "General English words for daily conversation",
    wordCount: 400,
    category: "general",
  },
];

export const mockWords: Word[] = [
  {
    id: "w-1",
    word: "allocate",
    phonetic: "/ˈaeləkeɪt/",
    definition: "to give something officially to someone for a particular purpose",
    example: "The school allocated more time for project-based learning.",
    exampleZh: "学校为项目式学习分配了更多时间。",
    bookId: "cet4-core",
    difficulty: "medium",
  },
  {
    id: "w-2",
    word: "retain",
    phonetic: "/rɪˈteɪn/",
    definition: "to continue to have something; keep",
    example: "Reviewing after one day helps you retain new words.",
    exampleZh: "隔天复习有助于你记住新单词。",
    bookId: "cet4-core",
    difficulty: "easy",
  },
  {
    id: "w-3",
    word: "coherent",
    phonetic: "/koʊˈhɪrənt/",
    definition: "logical and well organized; easy to understand",
    example: "A coherent essay has a clear structure and transitions.",
    exampleZh: "一篇连贯的文章有清晰的结构和过渡。",
    bookId: "ielts-bridge",
    difficulty: "hard",
  },
  {
    id: "w-4",
    word: "simulate",
    phonetic: "/ˈsɪmjəleɪt/",
    definition: "to copy or reproduce the conditions of something",
    example: "The app can simulate real exam pressure.",
    exampleZh: "这个应用可以模拟真实考试压力。",
    bookId: "ielts-bridge",
    difficulty: "medium",
  },
  {
    id: "w-5",
    word: "grateful",
    phonetic: "/ˈgreɪtfəl/",
    definition: "feeling or showing thanks",
    example: "I am grateful for your detailed feedback.",
    exampleZh: "我很感谢你详细的反馈。",
    bookId: "daily-english",
    difficulty: "easy",
  },
  {
    id: "w-6",
    word: "resilient",
    phonetic: "/rɪˈzɪliənt/",
    definition: "able to recover quickly after difficulties",
    example: "Resilient learners keep practicing after mistakes.",
    exampleZh: "有韧性的学习者会在犯错后继续练习。",
    bookId: "daily-english",
    difficulty: "medium",
  },
];

export const mockLearningRecords: LearningRecord[] = [
  {
    wordId: "w-1",
    bookId: "cet4-core",
    learnDate: "2026-03-10",
    status: "reviewing",
    nextReviewDate: "2026-03-15",
    interval: 3,
    easeFactor: 2.4,
    reviewCount: 2,
    successCount: 2,
    failureCount: 0,
    lastReviewedAt: "2026-03-13",
    retentionScore: 1,
  },
  {
    wordId: "w-2",
    bookId: "cet4-core",
    learnDate: "2026-03-11",
    status: "mastered",
    nextReviewDate: "2026-03-22",
    interval: 7,
    easeFactor: 2.6,
    reviewCount: 4,
    successCount: 4,
    failureCount: 0,
    lastReviewedAt: "2026-03-14",
    retentionScore: 1,
  },
  {
    wordId: "w-3",
    bookId: "ielts-bridge",
    learnDate: "2026-03-09",
    status: "reviewing",
    nextReviewDate: "2026-03-15",
    interval: 2,
    easeFactor: 2.1,
    reviewCount: 2,
    successCount: 1,
    failureCount: 1,
    lastReviewedAt: "2026-03-12",
    retentionScore: 0,
  },
  {
    wordId: "w-5",
    bookId: "daily-english",
    learnDate: "2026-03-12",
    status: "learning",
    nextReviewDate: "2026-03-15",
    interval: 1,
    easeFactor: 2.0,
    reviewCount: 1,
    successCount: 1,
    failureCount: 0,
    lastReviewedAt: "2026-03-14",
    retentionScore: 1,
  },
];

export const mockStudyEvents: StudyEvent[] = [
  { date: "2026-03-10", type: "learn", grade: "good", success: true },
  { date: "2026-03-11", type: "learn", grade: "good", success: true },
  { date: "2026-03-12", type: "review", grade: "good", success: true },
  { date: "2026-03-13", type: "review", grade: "hard", success: true },
  { date: "2026-03-14", type: "review", grade: "again", success: false },
  { date: "2026-03-15", type: "learn", grade: "good", success: true },
  { date: "2026-03-15", type: "review", grade: "good", success: true },
  { date: "2026-03-15", type: "relearn", grade: "again", success: false },
];

export function getWordsByBookId(bookId: string): Word[] {
  return mockWords.filter((word) => word.bookId === bookId);
}
